In [1]:
import numpy as np

### Consider the below code to answer further questions:
import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [5]:
import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object = list_)

print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


#### Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [7]:
import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object = list_)

print("Data typw of elements in list_:")
for item in list_:
    print(type(item))

print("Data type of elements in array_list:")
for item in array_list:
    print(type(item))

Data typw of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data type of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


#### Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [8]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']

array_list = np.array(list_, dtype=int)

print("Data type of elements in list_:")
for item in list_:
    print(type(item))

print("Data type of elements in array_list:")
for item in array_list:
    print(type(item))

Data type of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data type of elements in array_list:
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


#### Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [9]:
import numpy as np

num_list = [[1,2,3], [4,5,6]]
num_array = np.array(num_list)
shape = num_array.shape

size = num_array.size

print("It is the Shape of this array: ", shape)

print("it is the size of this Array: ", size)

It is the Shape of this array:  (2, 3)
it is the size of this Array:  6


##### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [10]:
import numpy as np

zero_matrix = np.zeros((3, 3))

print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [11]:
import numpy as np

identity_metrix = np.eye(5)

print(identity_metrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
